import type { NorrixConfig } from '@norrix/cli';

/**
 * Norrix CLI Configuration
 * Generated by norrix build command
 * 
 * For more options, see: https://norrix.net/docs/configuration
 */
export default {
  ios: {
    teamId: 'ARKDEV0022',
    distributionType: 'adhoc',
  },
  defaultPlatform: 'ios',
} satisfies NorrixConfig;
